name: Release

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
 release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.${{ github.run_number }}
          release_name: 1.0.${{ github.run_number }}
          body: |
            CI Release for 1.0.${{ github.run_number }}
          draft: false
          prerelease: false
